### ISSUE TITLE
clearwater-cassandra messes with /etc/init.d/cassandra

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/clearwater-cassandra#16]
This causes issues during install/update if the Cassandra package decides to change the file.  This also leads to the same problem as in https://github.com/Metaswitch/clearwater-infrastructure/issues/121 if `clearwater-infrastructure`, `cassandra` and `clearwater-cassandra` are installed simultaneously.

**Comment by bossmc** [comment]
As a workaround, if you hit this issue and `dpkg` prompts you to keep maintainers or original, chose maintainers and then restart `clearwater-infrastructure` to apply the appropriate modifications.

**Comment by mirw** [comment]
Bumping this to high priority.  We had marked it as low priority as it's only a problem if we need to upgrade Cassandra.  However, I think this means that we'd need 2 releases in order to perform this upgrade - one to fix this issue and another to actually do the upgrade.  It's possible that we might need to upgrade Cassandra faster than that (e.g. if a critical security vulnerability was found in Cassandra), so I think we need to either

*   have a concrete plan for how we could fix this and upgrade Cassandra in the same release or
*   fix this now (and hope that we don't need to upgrade Cassandra urgently).

**Comment by mirw** [comment]
@graemerobertson, over to you to take a look.

**Comment by mirw** [comment]
@graemerobertson, over to you.

**Comment by graemerobertson** [comment]
@rkd-msw did you fix something similar to this for memcached? Might be a good one for you to look at.

**Comment by rkd-msw** [comment]
I "fixed" this for memcached in the "we started building our own memcached package so didn't need to run sed commands over the init files from a separate package" sense. Nonetheless, I'll take a look.

**Comment by rkd-msw** [comment]
Links from researching this:

http://debathena.mit.edu/config-package-dev/
http://manpages.ubuntu.com/manpages/precise/man8/dpkg-divert.8.html
http://askubuntu.com/questions/116768/providing-a-customized-config-file-for-another-package

**Comment by rkd-msw** [comment]
Fixed by #79.
